[package]
name = "par_try"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray="*"
rayon="*"
ndarray-rand="*"
ndarray-linalg={version="*",features=["intel-mkl"]}
